cm7           ::= EOL* configs EOL+ song

configs       ::= key_config
key_config    ::= "key" WS? "=" WS? note
note          ::= [ACDFG] "#" | [ABDEG] "b" | [A-G]

song          ::= section? (EOL+ section?)*

section       ::= ("::" WS* section_label WS* "::" EOL)? line (EOL line)*
section_label ::= [^:]+

line          ::= WS* (EMPTY_LINE | chord_line) WS* (EOL WS* (EMPTY_LINE | lyrics_line) WS*)

chord_line    ::= chord (WS+ chord)*
chord         ::= relative_note quality? addition* base?
quality       ::= "mM7" | "m7b5" | "m7" | "m" | "sus2" | "sus4" |"7" | "M7" | "6" | "9" | "aug7" | "aug" | "dim7" | "dim"
addition      ::= "add" modifier? interval
base          ::= "/" relative_note
relative_note ::= ("1" | "2" | "3" | "4" | "5" | "6" | "7") ("#" | "b")?
interval      ::= "2" | "4" | "6" | "9" | "11" | "13"
modifier      ::= "#" | "b"

lyrics_line   ::= lyrics? (lyrics_beat+ lyrics?)*
lyrics        ::= [^\n\r()]+
lyrics_beat   ::= "(" lyrics? ")"

EMPTY_LINE    ::= "-"+

WS            ::= [ \t]+
EOL           ::= [\n\r]

